### ISSUE TITLE
Secrets module does not create one-time-pads.

### ISSUE THREAD

**Issue by maqp** [zevlee/footprint-otp#12]
One-time-pad is a bit of an odd bird in the world of cryptography, as it has exact requirements

1. The pad must be truly random. In other words, you can not use any algorithm to create the one-time pad, but a [HWRNG](https://en.wikipedia.org/wiki/Hardware_random_number_generator). Your application is using the `secrets.token_bytes()` method, which is a wrapper for `os.urandom()` which in turn reads from the kernel CSPRNG algorithm. the PR in CSPRNG stand's for pseudo-random, which is not the same.

2. One-time pad is an optimal cipher among the ciphers that provide `perfect secrecy`, as it satisfies the "key must be at least as long as the message" condition with equality. The kernel CSPRNG is usually seeded from the CPU's HWRNG and/or the chaotic events (interrupt events etc.) that happen during the use, but as the kernel CSPRNG expands the computationally secure seed, it does not provide perfect secrecy, only computational security.

XORing plaintext with keystream is what all [stream ciphers](https://en.wikipedia.org/wiki/Stream_cipher) do. Since the kernel CSPRNG is ChaCha20 stream cipher on Linux and AES on Windows, you're effectively using either ChaCha20 or AES encryption, with pre-shared keystream. 

Please strongly consider removing all references to OTP, or change the system to utilize a hardware random number generator.

**Comment by zevlee** [comment]
Thank you for providing such a detailed description of the shortcoming of my encryption implementation. I will work to change the system to use a hardware random number generator. In the meantime, I will add a disclaimer to the description of this project.

**Comment by maqp** [comment]
The user will probably want to choose and use one selected by themselves. E.g. https://github.com/atoponce/awesome-hwrng has a good list of HWRNGs. That repo was last updated 4 years ago, so I'm not sure what the current availability is. Also, I'm uncertain what type of API they provide, e.g. do most of them work out of the box and allow reading from `/dev/hwrng` or do they require vendor's drivers. 

Regarding the other ticket, if you insist on working on OTPs you'll want to look into one-time MACs or Carter-Wegman MACs for authentication and add the standard disclaimer to your readme:

>Warning! This project is a toy intended as a tool for myself to learn about cryptography. DO NOT USE IT IN PRODUCTION!

Bear in mind that OTPs aren't needed these days. OTP was the practically unbreakable option in the days when [cipher machines](https://www.cryptomuseum.com/crypto/index.htm) were the size of a typewriter, yet their security was generations behind what we use in our smart watches in 2022.

Modern 256-bit symmetric ciphers like AES-GCM and XChaCha20-Poly1305 handle message authentication for you, are secure until the universe dies of heat death, they're more convenient, and can use public key cryptography as convenient key exchange.

**Comment by zevlee** [comment]
The program has now been changed to use a user-selected key. References to one-time pad have been eliminated except for the title of the project.

**Comment by maqp** [comment]
Excellent attitude and reaction, bravo!

I'll leave a few excellent pieces of material to really get you started with the field, in the order of increasing breadth, depth (and difficulty):

1. [Information Theory](https://www.youtube.com/watch?v=69-YUSazuic&list=PLbg3ZX2pWlgKDVFNwn9B63UhYJVIerzHL) and [Cryptography](https://www.youtube.com/watch?v=lICOtR078Gw&list=PLB4D701646DAF0817) by Art of The Problem
1. https://www.crypto101.io/
2. [Serious Cryptography by JP Aumasson](https://nostarch.com/seriouscrypto)
3. [Cryptography I](https://www.coursera.org/learn/crypto) and [Cryptography II](https://www.coursera.org/learn/crypto2) by Dan Boneh
4. [Cryptography for Master's students](https://toc.cryptobook.us/) by Dan Boneh and Victor Shoup

The two best places to ask about the topic are

https://crypto.stackexchange.com/ and https://www.reddit.com/r/crypto

Best of luck to you!
